EMG/Controllers/ReplyController.cs
using AutoMapper;
using EMG.Interface;
using EMG.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EMG.Controllers
{
    [Authorize]
    public class ReplyController : Controller
    {
        private IUserServices _userServices;
        private IMessageServices _messageServices;
        private IReplyServices _replyServices;
        public ReplyController(IUserServices userServices, IMessageServices messageServices, IReplyServices replyServices)
        {
            this._replyServices = replyServices;
            this._messageServices = messageServices;
            this._userServices = userServices;
        }


        #region 開始頁面
        public ActionResult Index(int mId, string Identity, string Role)
        {
            ViewData["M_Id"] = mId;
            return PartialView();
        }
        #endregion

        #region 回覆陣列
        public ActionResult DataList(int mId, string Identity, string Role, int page = 1)
        {
            ReplyListView data = new ReplyListView();
            data.Paging = new ForPaging(page);
            data.mId = mId;
            data.Identity = Identity;
            data.Role = Role;
            data.DataList = _replyServices.GetDataList(data.Paging, data.mId);
            return PartialView(data);
        }
        #endregion

        #region 新增回覆
        public ActionResult Create(int mId)
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(ReplyCreatView newData, int mId)
        {
            var account = _userServices.GetAccount(User.Identity.Name);
            var photo = _userServices.Get(account).Url;
            newData.Account = User.Identity.Name;
            newData.Photo = photo;
            newData.mId = mId;
            newData.ReplyTime = DateTime.Now;
            Reply data = Mapper.Map<Reply>(newData);
            _replyServices.Insert(data);
            return RedirectToAction("Index", "Message");
        }
        #endregion

        #region 修改回覆
        public ActionResult Edit(int rId)
        {
            Reply data = _replyServices.GetDataById(rId);
            ReplyView nowData = Mapper.Map<ReplyView>(data);
            return PartialView(nowData);
        }
        [HttpPost]
        public ActionResult Edit(ReplyView nowData)
        {
            nowData.Account = User.Identity.Name;
            nowData.ReplyTime = DateTime.Now;
            var data = Mapper.Map<Reply>(nowData);
            _replyServices.Update(data);
            return RedirectToAction("Index", "Message");
        }
        #endregion

        #region 刪除回復
        public ActionResult Delete(int rId)
        {
            Reply data = _replyServices.GetDataById(rId);
            _replyServices.Delete(data);
            return RedirectToAction("Index", "Message");
        }
        #endregion
    }
}

EMG/Views/Reply/Create.cshtml
@model EMG.Model.ReplyCreatView
@{
    ViewBag.Title = "Create";
    Layout = null;
}
@using (Ajax.BeginForm("Create", "Reply", new AjaxOptions { InsertionMode = InsertionMode.Replace, UpdateTargetId = "MessageList" }))
{
    <table>
        <tr>
            <td>
                @Html.DisplayNameFor(m => m.Account)
                @User.Identity.Name
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(m => m.mId)
                @Html.TextBoxFor(m => m.mId, new { mId = ViewData, @readonly = true })
            </td>
        </tr>
        <tr>
            <td>
                新增回覆：
                @Html.TextBoxFor(m => m.Replys) 
                <input type="submit" value="回覆留言" />   
            </td>
        </tr>
    </table>  
}

EMG/Views/Reply/DataList.cshtml
@model EMG.Model.ReplyListView
@{
    ViewBag.Title = "DataList";
}

    @if (!Model.DataList.Count.Equals(0))
    {
        <table border="1" width="500">
            <tr>
                <td colspan="4">
                    留言回覆
                </td>
            </tr>
            @foreach (var item in Model.DataList)
            {
                <tr>
                    <td width="440">
                        @item.Account 說： @item.Replys<br />
                        @Html.DisplayNameFor(m => m.ReplyTime)
                        @item.ReplyTime
                    </td>
                    <td>
                         @if(User.Identity.Name == item.Account)
                         {
                             @Html.ActionLink("修改回覆", "Edit", new { rId = item.RId })
                             @Html.ActionLink("刪除留言", "Delete", new { rId = item.RId })
                         }
                    </td>
                </tr>
            }
        </table>
    }

EMG/Views/Reply/Edit.cshtml
@model EMG.Model.ReplyView
@{
    ViewBag.Title = "修改回覆";
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
    <h4>修改回覆</h4>
    @using (Html.BeginForm())
    {
        <table border="1">

            <tr>
                <td>
                    @Html.LabelFor(m => m.Account)
                </td>
                <td>
                    @User.Identity.Name
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(m => m.mId)             
                </td>
                <td>
                    @Html.TextBoxFor(m => m.mId, new { mId = ViewData, @readonly = true })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(m => m.Replys)
                </td>
                <td>
                    @Html.TextAreaFor(m => m.Replys)
                    @Html.ValidationMessageFor(m => m.Replys)
                </td>
            </tr>
        </table>
        <input type="submit" value="修改回覆" />
    }

EMG/Views/Reply/Index.cshtml
<div id="DataList">
    @Html.Action("DataList", "Reply", new { M_Id = ViewData["M_Id"] })
</div>
<div id="Create">
    @Html.Action("Create", "Reply")
</div>